AWSTemplateFormatVersion: 2010-09-09
Description: >-
  save data to db

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        DEBUG: true
        AccessKey: '{{resolve:ssm:AccessKey:1}}'
        SecretKey: '{{resolve:ssm:SecretKey:1}}'

Resources:
  SaveUserHistory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: function.handler
      Runtime: nodejs12.x
      Events:
        SaveUserHistory:
          Type: Api
          Properties:
            Path: /save
            Method: post
      Role: arn:aws:iam::355151872526:role/joeslambda
      # Policies:
      #   - AWSLambdaBasicExecutionRole

Outputs:
  SaveUserHistory:
    Description: save data to db
    Value: !GetAtt SaveUserHistory.Arn